"""Initial migration.

Revision ID: 653bed8a65fd
Revises: 
Create Date: 2024-07-01 16:12:49.072856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653bed8a65fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'label', ['label_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('label_id')

    # ### end Alembic commands ###
